language: objective-c
script: xcodebuild -project KalturaClient/KalturaClient.xcodeproj && export PATH=~/:$PATH &&  xcodebuild -project KalturaClientTester/KalturaClientTester.xcodeproj
#xcode_project: KalturaClient/KalturaClient.xcodeproj
#xcode_scheme: KalturaClient
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
