language: objective-c
script: xcodebuild -project KalturaClient/KalturaClient.xcodeproj  && touch ~/codesign && chmod +x ~/codesign && export PATH=~/:$PATH &&  xcodebuild -project KalturaClientTester/KalturaClientTester.xcodeproj 
