language: objective-c
before_script:
- ./add-key.sh
script: xcodebuild -project KalturaClient/KalturaClient.xcodeproj CODE_SIGNING_REQUIRED=NO && export PATH=~/:$PATH &&  xcodebuild CODE_SIGNING_REQUIRED=NO -project KalturaClientTester/KalturaClientTester.xcodeproj
#xcode_project: KalturaClient/KalturaClient.xcodeproj
#xcode_scheme: KalturaClient
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
