language: objective-c
#before_script:
#- ./add-key.sh
script: xcodebuild -project KalturaClient/KalturaClient.xcodeproj -sdk iphonesimulator VALID_ARCHS="arm64 armv7 i386 x86_64" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" && export PATH=~/:$PATH &&  xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" VALID_ARCHS="arm64 armv7 i386 x86_64" -project KalturaClientTester/KalturaClientTester.xcodeproj -sdk iphonesimulator
#xcode_project: KalturaClient/KalturaClient.xcodeproj
#xcode_scheme: KalturaClient
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
